Set expiration condition on ecs pr pipeline

diff --git a/azure/cleanup-ecs-pr-proxies.yml b/azure/cleanup-ecs-pr-proxies.yml
--- a/azure/cleanup-ecs-pr-proxies.yml
+++ b/azure/cleanup-ecs-pr-proxies.yml
@@ -35,11 +35,6 @@ jobs:
           echo working directory: $(System.DefaultWorkingDirectory)
         displayName: print aws info
 
-      - template: ./components/aws-assume-role.yml
-        parameters:
-          role: "auto-ops"
-          profile: "apm_ptl"
-
       - bash: |
           tfenv use 0.14.6
         displayName: setup terraform
@@ -48,7 +43,39 @@ jobs:
           make install
         displayName: install dependencies
 
+      - template: ./components/aws-assume-role.yml
+        parameters:
+          role: "auto-ops"
+          profile: "apm_ptl"
+
+      - bash: |
+          export retain_hours=72
+          sleep 90
+          ANSIBLE_FORCE_COLOR=yes make -C ansible remove-old-ecs-pr-deploys > /tmp/err.txt
+          ERROR_CODE=$?
+          ROLE_TIMEOUT_MSG="The AWS assume role session token is due to expire"
+          if grep -q "$ROLE_TIMEOUT_MSG" /tmp/err.txt ; then
+            echo "stderr for ansible has the error \"$ROLE_TIMEOUT_MSG\""
+            echo "Re-assuming role and re-running step"
+            echo "##vso[task.setvariable variable=has_aws_role_timedout;]true"
+
+          elif [ $ERROR_CODE -ne 0 ] ; then 
+            echo "ansible has unhandled error, re-raising"
+            >&2 cat /tmp/err.txt
+            exit -1
+          fi
+          cat /tmp/err.txt
+
+        displayName: "cleanup older pr deploys"
+
+      - template: ./components/aws-assume-role.yml
+        parameters:
+          role: "auto-ops"
+          profile: "apm_ptl"
+
       - bash: |
           export retain_hours=72
           ANSIBLE_FORCE_COLOR=yes make -C ansible remove-old-ecs-pr-deploys
-        displayName: "cleanup older pr deploys"
+        displayName: "retry cleanup older pr deploys on session role timeout"
+        condition: eq(variables['has_aws_role_timedout'], 'true')
+
